### ISSUE TITLE
Incorrect handling of invalid command names

### ISSUE THREAD

**Issue by PythonTryHard** [python-discord/sir-lancebot#1090]
## Description
Sir Lancebot handles certain prefix "commands" incorrectly, invoking multiple commands at the same time and tossing "Did you mean:" embed box after ward

## Steps to Reproduce
1. Invoke Lancebot with `.ha`
	- This issue also appears with prefix command lookalikes (`".....hah?"`)
	- This issue does not appear for `"..."`

## Actual Behaviour
![image](https://user-images.githubusercontent.com/31789326/185578561-559ec258-4786-4ef9-aa1a-f398e6d442ed.png)

## Expected Behaviour
As per screenshot and deductions made in `#dev-contrib`, Lancebot appears to be attempting to run multiple commands. In this case, Lancebot should send an embed prompting user to disambiguate the command 

## Additional Details
@TizzySaurus (`<@!442244135840382978>`) asked me to mention that #1064 might be a likely cause of the bug:
![image](https://user-images.githubusercontent.com/31789326/185579122-9ac4d414-e5f9-4a1e-a04c-7946b16633f9.png)
![image](https://user-images.githubusercontent.com/31789326/185579125-8ba56436-84bb-4b46-8d3c-5c026269a8e2.png)

## Would you like to implement a fix?
- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

**Comment by TizzySaurus** [comment]
After looking briefly into #1064, it looks like the issue is [these lines](https://github.com/python-discord/sir-lancebot/blob/3b891955a150ef5a6c47d2ab389348a5de8ef38e/bot/exts/core/error_handler.py#L170-L177).
```python
                try:
                    if not await similar_command.can_run(ctx):
                        log.debug(log_msg)
                        continue
                except commands.errors.CommandError as cmd_error:
                    log.debug(log_msg)
                    await self.on_command_error(ctx, cmd_error)
                    continue
```
I believe we need to remove the call to `on_command_error`. Note that prior to #1064 we called `on_command_error` so removing the call may break other parts of the bot that call this function (would have to check to see what's best implementation wise).

I also noted that the [get_command_suggestions](https://github.com/python-discord/sir-lancebot/blob/3b891955a150ef5a6c47d2ab389348a5de8ef38e/bot/utils/commands.py#L6-L11) util that was added has an incorrect return type-hint of `Optional[list]` instead of just `list`, which we may as well fix at the same time.
