### ISSUE TITLE
Expand the holiday-based comment reaction to cover more than just Halloween

### ISSUE THREAD

**Issue by thurisatic** [python-discord/sir-lancebot#1165]
## Description & Reasoning
While it's entertaining that Sir Lancebot reacts to comments containing certain words during Halloween (more accurately, all of October), it seems mildly unfair that this feature is specific to Halloween. Surely other events - notably Christmas - deserve such entertainment as well? This issue proposes adding more events to the reaction feature.

## Proposed Implementation
Implementation involves upping the number of reactable "holidays" to 7, with some having a regex trigger resulting in one of a few randomly-chosen reactions:
 - Valentines (discord reaction `:heart:`❤️)
 - Easter (`:rabbit:`🐰 or `:rabbit2:`🐇 ; `:egg:`🥚)
 - Earth Day (`:earth_africa:`🌍  `:earth_americas:`🌎 or `:earth_asia:`🌏)
 - Pride Month (`:rainbow_flag:`🏳️‍🌈)
 - Halloween (no change)
 - Hanukkah (`:menorah:` 🕎)
 - Christmas (`:snowman:`⛄ or `:snowman2:`☃️ ; `:snowflake:`❄️ ; `:santa:`🎅 ; `:christmas_tree:`🎄 ; `:deer:`🦌
Other than Christmas, these are taken from pre-existing folders in the `bot/exts/holidays` directory. In addition, the implementation would move `holidays/halloween/spookyreact.py` to an all-events `holidays/holidayreact.py`, preventing the existence or need of very non-DRY near-duplicates in 7 different folders (and thus 7 Cogs).

![lancebot_reactions_test](https://user-images.githubusercontent.com/99002593/207473382-e3e1f73c-8606-4030-8014-cc6fe2425ae9.png)
Note a few things in this screenshot:
 - The reaction for "snowman" is randomly chosen, but only one occurs per message
 - `flake8` is excluded in the snowflake trigger regex (but this can be changed)
 - *All* November (just Hanukkah) and December (Hanukkah and Christmas) reactions are featured
 - 🦌 on Discord is *not* the same as on GitHub - Discord's is a face-on view, GitHub's is in profile. `rainbow_flag`(🏳️‍🌈) is not in this image but also different, with Discord's having no flagpole - though this may change depending on OS and client.

## Additional Details
While this does increase reaction coverage to half of the year, note that most months have few reactions and thus few triggers. Even those that do - Halloween and Christmas - are unlikely to generate sufficient reaction rates to become spammy.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by wookie184** [comment]
This sounds like a nice idea, some thoughts:

Some events (e.g. Hanukkah) happen at different dates on different years. Is the idea that we pick a rough range that is fixed for these e.g. the whole of december? (I think that would probably be the best option)

> flake8 is excluded in the snowflake trigger regex (but this can be changed)

I'm sure this is what you meant anyway, but to confirm, we should match words exactly using `\b` word boundary markers in the regex (how it already works) to avoid this rather than special casing matches to avoid.

> While this does increase reaction coverage to half of the year, note that most months have few reactions and thus few triggers. Even those that do - Halloween and Christmas - are unlikely to generate sufficient reaction rates to become spammy.

Agree with this, and if it becomes an issue there are a bunch of things we'd be able to do (make regexes more strict, limit reactions to certain channels, reduce event durations).

I'll mark this as approved, feel free to open a PR if you're still interested!
