### ISSUE TITLE
`adventofcode.is_in_advent` has an incorrect docstring.

### ISSUE THREAD

**Issue by Starwort** [python-discord/sir-lancebot#318]
Can fix immediately but rules say I have to get the issue approved before I PR

**Comment by MarkKoz** [comment]
I do think this is an incorrect range rather than an incorrect docstring because AoC does have 25 days. @sco1 can you confirm?

**Comment by MarkKoz** [comment]
Never mind, it's intentionally up to the 24th to prevent scheduling things for the next day (26th), which would be after the event is over. However, I will point out the countdown command's message is inaccurate to say that AoC is no longer running when it's invoked on the 25th.

Regarding the docstring, I think it should be specified that the 25th is exclusive, or change it 24th and specify inclusive. Otherwise it is ambigous in English whether _between_ is inclusive or exclusive. This small change can be thrown in with #317.

**Comment by lemonsaurus** [comment]
Please make issues that actually explain what the issue is in the top comment.

that said, this seems fine, approved.
