### ISSUE TITLE
.xkcd command to get xkcd comics

### ISSUE THREAD

**Issue by CharlieADavies** [python-discord/sir-lancebot#377]
## Description
A command to retrieve xkcd comics (by number, most recent, or at random) and display them in an embed. Idea was first proposed by Discord user AG.

## Reasoning
XKCD comics are funny, and they are often relevant to a conversation. I think a command to let people find comics such as the the Bobby Tables comic https://xkcd.com/327/ or to discover new comics would be a cool feature.

## Proposed Implementation
XKCD have a JSON interface that can be used to retrieve comics and their relevant information. You can get either the latest comic, or a specific comic. The implementation would have 3 commands: 
`.xkcd latest`, to get the latest comic, `.xkcd [number]` to get a specific comic, and `.xkcd`/`.xkcd random` to retrieve a random comic.

The comics would then be displayed in an embed along with the title and a link.

## Additional Details
It would also be cool to retrieve comics by an alias (e.g `.xkcd bobby tables`, `.xkcd standards`, or `.xkcd git`) to get a specific comic, however that would require storing the aliases somewhere on the bot or manually searching every single xkcd - and I don't think there is any good implementation for that.

## Would you like to implement this yourself?
- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by sco1** [comment]
We could probably implement a persistent cache of at least the comic title & ID. Sites like [Explain XKCD](https://www.explainxkcd.com/wiki/index.php/Main_Page) do have [such tables](https://www.explainxkcd.com/wiki/index.php/List_of_all_comics) already, which would be an expensive cache for initial seed, with a smaller daily hit to update anything recent that is missing.

For deeper aliasing there are things like [Relevant XKCD](http://www.relevantxkcd.appspot.com/) that exist, but I'm not sure if they're constantly maintained or just a demonstration, or if they're acceptably queryable. I don't think implementing our own solution is in the scope of Seasonalbot, and manually aliasing is a non-starter. This is probably relevant to the above example since the ["bobby tables" XKCD](https://www.xkcd.com/327/) is titled "Exploits of a Mom", and getting to it from a "bobby tables" query requires deeper inspection.

Additional details aside, this would be a fun addition even as just a latest/id/random lookup.

**Comment by Den4200** [comment]
@CharlieADavies Are you still planning on working on this issue?

**Comment by CharlieADavies** [comment]
This kinda fell off my radar due to other real life things; sorry for not updating the issue or commenting.

I can (and would like to) implement this, but I won't be able to for a little while - so if someone else wants to work on this I can't really object.

**Comment by htudu** [comment]
@CharlieADavies @Den4200  I have been working and implemented it.
