### ISSUE TITLE
Verify channel constants on startup

### ISSUE THREAD

**Issue by Numerlor** [python-discord/sir-lancebot#393]
## Description
The bot should check that there are no channels missing from the guild which are present in the bot constants.

## Reasoning
As discussed in #342 this will help prevent issues like #335 and has already been implemented for bot.

## Proposed Implementation
With the current implementation of the constants as simple classes (not sure why they're NamedTuples) without any annotations or being an object that holds more info about itself, we can check their contents through the `vars` function and handling any non private names

Another potentially cleaner solution would be changing the classes to something like enums which are iterable and gives us only the values we want without any filtering

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [X] Anyone can implement this feature

Paging @neonsea  as they expressed interest in #342

**Comment by WillDaSilva** [comment]
I'd like to implement this

**Comment by WillDaSilva** [comment]
I've been playing around with alternatives for `NamedTuple` for the `Channels` class. I think it would be best to leave it as a named tuple, as its attributes are used all over the codebase as ints. It could be changed to an `IntEnum`, whose attributes subclass `int`, but some errors arise from that since the attributes don't behave exactly like ints do. Changing it to an `IntEnum` would require calling `int` on most/all of its uses, which is undesirable. Changing it to a regular `Enum` would make it difficult to use the attributes as ints at all. Iterating over the `__dict__` of the class (via `vars`) and filtering out anything which begins with an underscore seems like the way to go.
