### ISSUE TITLE
Add command for fun facts about Python

### ISSUE THREAD

**Issue by MrKomodoDragon** [python-discord/sir-lancebot#587]
## Description
A simple command that would give you fun facts about python itself.

## Reasoning
If people wanted to learn more about Python and get some trivia, this would be a useful command.

## Proposed Implementation
I was thinking of using a text/json file, and pick a random fact from that.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by kosayoda** [comment]
Hello. I like the idea, and I think we should discuss a couple more implementation details before proceeding.

What do you think would be a good name for the Cog? What about the command?

**Comment by Shivansh-007** [comment]
`.pyfacts` maybe?

**Comment by MrKomodoDragon** [comment]
I think `.pyfacts` is a good idea, like @Shivansh-007 said. About the cog, would py-facts work?

**Comment by Shivansh-007** [comment]
`PythonFacts` for the cog.

**Comment by MrKomodoDragon** [comment]
Yup

**Comment by MrKomodoDragon** [comment]
I made a concept of what it could look like:

![image](https://user-images.githubusercontent.com/74436682/107793393-18054b00-6d0b-11eb-8ca1-2d2794b42fa0.png)

**Comment by MrKomodoDragon** [comment]
So how is this idea?

**Comment by kosayoda** [comment]
Sold. Let's go with `PythonFacts` for the cog, and `.pythonfacts` as the command, and `pyfacts` as an alias.

Since you already provided the proof-of-concept, I think it'll look better with just the first word capitalized. The title could also be `Python Facts` rather than `Hey <username>!` just so it's clearer as to what the response is talking about.

Take it away!

**Comment by MrKomodoDragon** [comment]
Ok!
