### ISSUE TITLE
.quack - Procedural Duck Generator!

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/sir-lancebot#652]
## Description
A command to fetch a random duck from QuackStack.

https://github.com/python-discord/quackstack

## Proposed Implementation
This command can be called in two ways:
- With `.quack`, you simply get a completely random duck. Different every time.
- By using `.quack <seed>`, you'll get a duck that's always the same if the seed is the same.

## Is this blocked?
Probably. We need to get Quackstack to a more finished state before it will be possible to do this issue. If you're wondering if this issue is blocked, check if we've completed the [Quackstack v1.0.0 milestone](https://github.com/python-discord/quackstack/milestone/1).

## Would you like to implement this yourself?
- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by vcokltfre** [comment]
Hey, I'd like to take this up (see #693 lol)

**Comment by Kronifer** [comment]
Hey @lemonsaurus I'd love to take this!

**Comment by jb3** [comment]
@Kronifer vco is interested in taking this as shown above, but on top of that this issue is currently blocked pending futher development on QuackStack, there are a few things we need to do before we should slot it into a production application.

You are welcome to contribute to quackstack though, and I'm sure that if you ask in `#dev-contrib` then you can find out what needs to be done to get that project into a more ready state.

**Comment by Kronifer** [comment]
alright, sounds good joe, ive been looking into the readme

**Comment by Xithrius** [comment]
Stalled because of quackstack

**Comment by Shivansh-007** [comment]
If we decide to use the quackstack API, there shouldn't be any reason to stall this issue and it can be worked on. Otherwise, if we decide to use quackstack via a PyPI package and generate the duck images ourselves, we would need to wait for python-discord/quackstack#52.

There are downsides to both of them, if we use the API, anyone wanting to run the quack command on sir-Lancelot would need to have the API running and if we decide to use the PyPI package and generate the image ourselves, it would be consuming unnecessary memory.

**Comment by Xithrius** [comment]
I think we should wait for quackstack to be contained within a package.

**Comment by ChrisLovering** [comment]
Does quackstack not support api requests from the public? I don't understand why someone would need a version of quackstack running locally.

**Comment by Shivansh-007** [comment]
🤦🏾 You are right.

**Comment by ChrisLovering** [comment]
It would be nice to have sirlance use the internal cluster route in production, but then use the public api endpoint for local dev, just to save egress/ingress from the cluster

**Comment by Xithrius** [comment]
If we have those public API requests, that solves all our problems. Let's just go with that for now.

**Comment by Xithrius** [comment]
Whoever wants to pick this issue up, you're free to do so. Ping a core dev and we'll assign.

You can find all the docs stuff here: <https://quackstack.pythondiscord.com/docs>.

**Comment by Kronifer** [comment]
@Xithrius I'll take this on

**Comment by Xithrius** [comment]
@Kronifer Very well.
