### ISSUE TITLE
Allow bookmark command in every channel

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/sir-lancebot#827]
## Description

As discussed in https://github.com/python-discord/sir-lancebot/pull/816 we should allow the bookmark command to be allowed in every channel.

## Reasoning

Bookmarking messages is very useful for people who want to remember things, and the command itself doesn't use up much screen real-estate, so it shouldn't cause an issue

## Proposed Implementation

Possibly add the everyone role to the `whitelist_override` but I'll leave the details up to the developer.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by ChrisLovering** [comment]
@Objectivitix Since you did the first PR, I'll give you first dibs on this issue.

Do you want this? If not, I'll leave it open for others to pickup.

**Comment by Objectivitix** [comment]
@ChrisLovering I'll be on it, thanks! Will `role=(everyone role)` be enough? I'll look through the code tomorrow, currently about to sleep lol

**Comment by ChrisLovering** [comment]
Great, I'll assign you to the issue! I'm not too familiar with the check, but that might do it. Feel free to ask in #dev-contrib if you're having issues.

As always there's no rush, so take your time :)

**Comment by Objectivitix** [comment]
Thanks! I'd probably need a PyDis server clone, and since I haven't contributed for a while after the 3.9 and poetry upgrade, I'd need to update my Lance file as well to work with it. IIRC the instructions are in dev-announcements, so that's convenient :P

**Comment by Objectivitix** [comment]
I'm getting quite confused over the whitelist logic - it's scattered over multiple files and I tried implementing an `every` parameter in `in_whitelist_check` but didn't get any results. I'll try some more stuff tomorrow, but if all else fails, I'm thinking of just making an `Everywhere` class whose instances can be put into the `channels` param. The class will roughly look like this: ```py
class Everywhere:
    """Docstring"""

    def __contains__(self, item):
        return True
```And since the `in_whitelist_check` logic relies on the `in` operator with `Container[int]`s, this would actually be a quite intuitive solution. I'm still not sure if it'd work though, and if it's good practice, which is why I'm leaving it as a last resort. What are your thoughts on this, @ChrisLovering? If we come to the consensus that this is not what we want, and I genuinely can't find anything else to make it work, I'd have to pass this issue on to someone else.

**Comment by Objectivitix** [comment]
For now though, I still got some things I can try :P

**Comment by ChrisLovering** [comment]
It might be best asking in #dev-contrib, I haven't looked into the whitelist check myself, others might have.

**Comment by Objectivitix** [comment]
Me about to fall asleep:
My brain: hey, did you check the decorator type hints today? You might've simply reversed the order...
Me: no no shut up
Me brain: the solution to your bug was probably very simple
Me: ...

**Comment by Objectivitix** [comment]
`def inner(func: Callable) -> Callable:`
So yeah, I swapped it around xD I used the decorator on a command object
BRUH IT EXPLICITLY STATES TO USE ON THE FUNCTION ITSELF

**Comment by Objectivitix** [comment]
Update: lmao my late night brain was right, linting and making PR now
